# Generated by Django 4.2.6 on 2023-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(default=None, max_length=100)),
                ("date_of_birth", models.DateField()),
                ("image", models.ImageField(upload_to="images/")),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("education", models.TextField()),
                ("skills", models.TextField()),
                ("description", models.TextField(default=None)),
                ("create_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
